### ISSUE TITLE
running a command generates a seg fault error

### ISSUE THREAD

**Issue by baldwinSPC** [1and1/oneandone-cloudserver-cli#4]
When I don't have an API token set I get the error: 

$ oneandone server fixedsizes
Segmentation fault: 11

**Comment by nurfet-becirevic** [comment]
That's an odd error. When I don't have set the API key I receive the following error:
```
$ oneandone server fixedsizes
No API key specified, use either --apikey global option or environment variable ONEANDONE_API_KEY
```
